# Default values for fishing.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

namespace: official-web

image:
  repository: reg.ffglobaltech.com/official
  tag: latest
  pullPolicy: Always

nameOverride: "official"
fullnameOverride: "official"

service:
  type: ClusterIP
  ports:
    - name: tcp
      port: 80
      targetPort: 3000
      protocol: TCP

env:


imagePullSecrets:
  - name: "gcr-secret"

containerPorts:
  - name: tcp
    containerPort: 3000
    protocol: TCP

resources:
  requests:
    memory: "100Mi"
    cpu: "20m"
  limits:
    memory: "500Mi"
    cpu: "200m"

nodeSelector: {}

tolerations: []

affinity: {}
